Vagrant.configure("2") do |config|
  config.vm.box = "b2-tp4-centos"

  config.vbguest.auto_update = false
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true


  # Gitea node1
  config.vm.define "node1" do |node1|
    node1.vm.network "private_network", ip: "192.168.2.41"
    node1.vm.hostname = "node1.tp4.b2"
  
    node1.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.name = "node1.tp4.b2"
    end
    node1gitea.vm.provision "shell",
      path: "scripts/node1.sh
  end
    
  # MariaDB node2
  config.vm.define "node2" do |node2|
    node2.vm.network "private_network", ip: "192.168.2.42"
    node2.vm.hostname = "node2.tp4.b2"
  
    node2.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.name = "node2.tp4.b2"
    end
    node2bdd.vm.provision "shell",
      path: "scripts/node2.sh"
  end

  # NGINX node3
  config.vm.define "node3" do |node3|
    node3.vm.network "private_network", ip: "192.168.2.43"
    node3.vm.hostname = "node3.tp4.b2"
    
    node3.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.name = "node3.tp4.b2"

      end
    node3.vm.provision "shell",
      path: "scripts/node3.sh"
  end
  end

    # Serv NFS node 4
    config.vm.define "node4" do |node4|
      node4.vm.network "private_network", ip: "192.168.2.44"
      node4.vm.hostname = "node4.tp4.b2"
    
      node4.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.name = "node4.tp4.b2"
      end
      node4nfs.vm.provision "shell",
        path: "scripts/node4.sh"
    end
  end
end